### ISSUE TITLE
HEADS-UP: prometheus-zfs has landed in FreeBSD ports!

### ISSUE THREAD

**Issue by 0mp** [matusnovak/prometheus-zfs#2]
Hey,

I just wanted to let you know that I've packaged prometheus-zfs for FreeBSD: https://www.freshports.org/sysutils/py-prometheus-zfs

Cheers!

**Comment by matusnovak** [comment]
Thank you @0mp That's amazing work! I have added a link with your username to the readme.

**Comment by 0mp** [comment]
Thanks!
